"""removed attempt number

Revision ID: 094f884c61d6
Revises: ea86b26cbc0f
Create Date: 2026-06-16 13:35:03.208547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094f884c61d6'
down_revision: Union[str, Sequence[str], None] = 'ea86b26cbc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'attempt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('attempt', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
