"""added users

Revision ID: 384e3e669e83
Revises: 2bb9e6b0bb89
Create Date: 2026-09-17 11:54:52.501311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384e3e669e83'
down_revision: Union[str, Sequence[str], None] = '2bb9e6b0bb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.add_column('workflows', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflows_user_id_fkey', 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
