"""initial_schema

Revision ID: 47448dcc901f
Revises: 
Create Date: 2026-06-02 16:38:09.277158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47448dcc901f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('recipient', sa.Text(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_message_id', 'emails', ['message_id'], unique=False)
    op.create_table('poll_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('email_account', sa.Text(), nullable=False),
    sa.Column('imap_id', sa.Text(), nullable=False),
    sa.Column('uidvalidity', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imap_id', 'email_account', 'uidvalidity', name='_imap_account_uc')
    )
    op.create_index('idx_poll_log_message_id', 'poll_log', ['message_id'], unique=False)
    op.create_index('idx_poll_log_timestamp', 'poll_log', ['timestamp'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('content', postgresql.BYTEA(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('reference_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('normal_interval_hours', sa.Integer(), nullable=False),
    sa.Column('late_interval_hours', sa.Integer(), nullable=True),
    sa.Column('next_expected_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default='UTC', nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_successful', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_missed', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(), server_default='never_seen', nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('ok', 'missed', 'never_seen')", name='checkpoints_status_check'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('success', 'failed', 'skipped', 're_run', 'running', name='run_state'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('step', sa.Text(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('runs')
    op.drop_table('checkpoints')
    op.drop_table('attachments')
    op.drop_table('workflows')
    op.drop_index('idx_poll_log_timestamp', table_name='poll_log')
    op.drop_index('idx_poll_log_message_id', table_name='poll_log')
    op.drop_table('poll_log')
    op.drop_index('idx_email_message_id', table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
