"""imap adjustments

Revision ID: 49903a578ea9
Revises: 691db8575f9f
Create Date: 2026-06-30 14:03:01.323511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49903a578ea9'
down_revision: Union[str, Sequence[str], None] = '691db8575f9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_account', sa.Text(), nullable=False),
    sa.Column('mailbox', sa.Text(), nullable=False),
    sa.Column('uidvalidity', sa.Text(), nullable=True),
    sa.Column('last_seen_uid', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_account', 'mailbox', name='_mailbox_account_uc')
    )
    op.drop_index(op.f('idx_poll_log_message_id'), table_name='poll_log')
    op.drop_index(op.f('idx_poll_log_timestamp'), table_name='poll_log')
    op.drop_table('poll_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_account', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('imap_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('uidvalidity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('poll_log_pkey')),
    sa.UniqueConstraint('imap_id', 'email_account', 'uidvalidity', name=op.f('_imap_account_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_poll_log_timestamp'), 'poll_log', ['timestamp'], unique=False)
    op.create_index(op.f('idx_poll_log_message_id'), 'poll_log', ['message_id'], unique=False)
    op.drop_table('mailbox_state')
    # ### end Alembic commands ###
