"""runs cascade on wfl deletion

Revision ID: 691db8575f9f
Revises: 094f884c61d6
Create Date: 2026-06-23 15:36:06.282143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691db8575f9f'
down_revision: Union[str, Sequence[str], None] = '094f884c61d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('runs_workflow_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_workflow_id_fkey'), 'runs', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.alter_column('runs', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
